SET SQL DIALECT 3;
DROP TABLE CLIENTE;
DROP TABLE STATUS_NFE;
DROP TABLE ESTADOS;
DROP TABLE PAISES;
DROP TABLE FUNCIONARIOS;
DROP TABLE IBPT;
DROP TABLE NFE_ITENS;
DROP TABLE NFE_PAGAMENTO;
DROP TABLE NFE_CAB;
DROP TABLE VENDA;
DROP TABLE ESTOQUE;
DROP TABLE CONFIGURACAO;
DROP TABLE EMITENTE;


DROP GENERATOR GEN_CLIENTE_CODIGO;
DROP GENERATOR GEN_EMITENTE_REGISTRO;
DROP GENERATOR GEN_FUNCIONARIOS_ID;
DROP GENERATOR GEN_IBPT_COD;
DROP GENERATOR GEN_NFE_CAB_ID;
DROP GENERATOR GEN_NFE_ITENS_ID;
DROP GENERATOR GEN_NFE_PAGAMENTO_ID;
DROP GENERATOR GEN_VENDA_CODIGO;
DROP GENERATOR GEN_ESTOQUE_CODIGO_PRODUTO;
